name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.7'

      - name: Show Flutter version
        run: flutter --version

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Exclude from Windows Defender (Fix for mt.exe error)
        run: Add-MpPreference -ExclusionPath "${{ github.workspace }}"

      - name: Clean project
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows EXE
        run: flutter build windows --release

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/x64/runner/Release/
